[package]
name = "rlibbcachefs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cbindgen = "0.20.0"

[dependencies]
anyhow = "1.0.44"
bch_bindgen = { path = "../bch_bindgen/" }
